# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"I\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x18\n\x04role\x18\x04 \x01(\x0e\x32\n.auth.Role\"\'\n\x16TokenValidationRequest\x12\r\n\x05token\x18\x01 \x01(\t\"r\n\x17TokenValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x18\n\x04role\x18\x04 \x01(\x0e\x32\n.auth.Role\x12\x0e\n\x06reason\x18\x05 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"+\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User*6\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x0b\n\x07STUDENT\x10\x01\x12\x0b\n\x07\x46\x41\x43ULTY\x10\x02\x32\x93\x01\n\x0b\x41uthService\x12L\n\rValidateToken\x12\x1c.auth.TokenValidationRequest\x1a\x1d.auth.TokenValidationResponse\x12\x36\n\x07GetUser\x12\x14.auth.GetUserRequest\x1a\x15.auth.GetUserResponseB\x14\n\x10\x63om.stdiscm.authP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.stdiscm.authP\001'
  _globals['_ROLE']._serialized_start=332
  _globals['_ROLE']._serialized_end=386
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=93
  _globals['_TOKENVALIDATIONREQUEST']._serialized_start=95
  _globals['_TOKENVALIDATIONREQUEST']._serialized_end=134
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_start=136
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_end=250
  _globals['_GETUSERREQUEST']._serialized_start=252
  _globals['_GETUSERREQUEST']._serialized_end=285
  _globals['_GETUSERRESPONSE']._serialized_start=287
  _globals['_GETUSERRESPONSE']._serialized_end=330
  _globals['_AUTHSERVICE']._serialized_start=389
  _globals['_AUTHSERVICE']._serialized_end=536
# @@protoc_insertion_point(module_scope)
