# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'course.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ourse.proto\x12\x06\x63ourse\"X\n\x06\x43ourse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\x05 \x01(\x05\"\x14\n\x12ListCoursesRequest\"6\n\x13ListCoursesResponse\x12\x1f\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x0e.course.Course\":\n\x10GetCourseRequest\x12\x0c\n\x02id\x18\x01 \x01(\tH\x00\x12\x0e\n\x04\x63ode\x18\x02 \x01(\tH\x00\x42\x08\n\x06lookup\"3\n\x11GetCourseResponse\x12\x1e\n\x06\x63ourse\x18\x01 \x01(\x0b\x32\x0e.course.Course2\x99\x01\n\rCourseService\x12\x46\n\x0bListCourses\x12\x1a.course.ListCoursesRequest\x1a\x1b.course.ListCoursesResponse\x12@\n\tGetCourse\x12\x18.course.GetCourseRequest\x1a\x19.course.GetCourseResponseB\x16\n\x12\x63om.stdiscm.courseP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.stdiscm.courseP\001'
  _globals['_COURSE']._serialized_start=24
  _globals['_COURSE']._serialized_end=112
  _globals['_LISTCOURSESREQUEST']._serialized_start=114
  _globals['_LISTCOURSESREQUEST']._serialized_end=134
  _globals['_LISTCOURSESRESPONSE']._serialized_start=136
  _globals['_LISTCOURSESRESPONSE']._serialized_end=190
  _globals['_GETCOURSEREQUEST']._serialized_start=192
  _globals['_GETCOURSEREQUEST']._serialized_end=250
  _globals['_GETCOURSERESPONSE']._serialized_start=252
  _globals['_GETCOURSERESPONSE']._serialized_end=303
  _globals['_COURSESERVICE']._serialized_start=306
  _globals['_COURSESERVICE']._serialized_end=459
# @@protoc_insertion_point(module_scope)
