# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import enrollment_pb2 as enrollment__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in enrollment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnrollmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_unary(
                '/enrollment.EnrollmentService/Enroll',
                request_serializer=enrollment__pb2.EnrollRequest.SerializeToString,
                response_deserializer=enrollment__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.ListStudentEnrollments = channel.unary_unary(
                '/enrollment.EnrollmentService/ListStudentEnrollments',
                request_serializer=enrollment__pb2.ListStudentEnrollmentsRequest.SerializeToString,
                response_deserializer=enrollment__pb2.ListStudentEnrollmentsResponse.FromString,
                _registered_method=True)
        self.DropEnrollment = channel.unary_unary(
                '/enrollment.EnrollmentService/DropEnrollment',
                request_serializer=enrollment__pb2.DropEnrollmentRequest.SerializeToString,
                response_deserializer=enrollment__pb2.DropEnrollmentResponse.FromString,
                _registered_method=True)


class EnrollmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Enroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStudentEnrollments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropEnrollment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnrollmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=enrollment__pb2.EnrollRequest.FromString,
                    response_serializer=enrollment__pb2.EnrollResponse.SerializeToString,
            ),
            'ListStudentEnrollments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStudentEnrollments,
                    request_deserializer=enrollment__pb2.ListStudentEnrollmentsRequest.FromString,
                    response_serializer=enrollment__pb2.ListStudentEnrollmentsResponse.SerializeToString,
            ),
            'DropEnrollment': grpc.unary_unary_rpc_method_handler(
                    servicer.DropEnrollment,
                    request_deserializer=enrollment__pb2.DropEnrollmentRequest.FromString,
                    response_serializer=enrollment__pb2.DropEnrollmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'enrollment.EnrollmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('enrollment.EnrollmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnrollmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrollment.EnrollmentService/Enroll',
            enrollment__pb2.EnrollRequest.SerializeToString,
            enrollment__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStudentEnrollments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrollment.EnrollmentService/ListStudentEnrollments',
            enrollment__pb2.ListStudentEnrollmentsRequest.SerializeToString,
            enrollment__pb2.ListStudentEnrollmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropEnrollment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrollment.EnrollmentService/DropEnrollment',
            enrollment__pb2.DropEnrollmentRequest.SerializeToString,
            enrollment__pb2.DropEnrollmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
