# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grade.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grade.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgrade.proto\x12\x05grade\"]\n\x0bGradeRecord\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nstudent_id\x18\x02 \x01(\t\x12\x11\n\tcourse_id\x18\x03 \x01(\t\x12\x0c\n\x04term\x18\x04 \x01(\t\x12\r\n\x05grade\x18\x05 \x01(\t\"X\n\x12SubmitGradeRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x11\n\tcourse_id\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\t\x12\r\n\x05grade\x18\x04 \x01(\t\"9\n\x13SubmitGradeResponse\x12\"\n\x06record\x18\x01 \x01(\x0b\x32\x12.grade.GradeRecord\"\'\n\x11ListGradesRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\"8\n\x12ListGradesResponse\x12\"\n\x06grades\x18\x01 \x03(\x0b\x32\x12.grade.GradeRecord2\x97\x01\n\x0cGradeService\x12\x44\n\x0bSubmitGrade\x12\x19.grade.SubmitGradeRequest\x1a\x1a.grade.SubmitGradeResponse\x12\x41\n\nListGrades\x12\x18.grade.ListGradesRequest\x1a\x19.grade.ListGradesResponseB\x15\n\x11\x63om.stdiscm.gradeP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grade_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.stdiscm.gradeP\001'
  _globals['_GRADERECORD']._serialized_start=22
  _globals['_GRADERECORD']._serialized_end=115
  _globals['_SUBMITGRADEREQUEST']._serialized_start=117
  _globals['_SUBMITGRADEREQUEST']._serialized_end=205
  _globals['_SUBMITGRADERESPONSE']._serialized_start=207
  _globals['_SUBMITGRADERESPONSE']._serialized_end=264
  _globals['_LISTGRADESREQUEST']._serialized_start=266
  _globals['_LISTGRADESREQUEST']._serialized_end=305
  _globals['_LISTGRADESRESPONSE']._serialized_start=307
  _globals['_LISTGRADESRESPONSE']._serialized_end=363
  _globals['_GRADESERVICE']._serialized_start=366
  _globals['_GRADESERVICE']._serialized_end=517
# @@protoc_insertion_point(module_scope)
