# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grade_pb2 as grade__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grade_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GradeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitGrade = channel.unary_unary(
                '/grade.GradeService/SubmitGrade',
                request_serializer=grade__pb2.SubmitGradeRequest.SerializeToString,
                response_deserializer=grade__pb2.SubmitGradeResponse.FromString,
                _registered_method=True)
        self.ListGrades = channel.unary_unary(
                '/grade.GradeService/ListGrades',
                request_serializer=grade__pb2.ListGradesRequest.SerializeToString,
                response_deserializer=grade__pb2.ListGradesResponse.FromString,
                _registered_method=True)


class GradeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitGrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GradeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitGrade': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGrade,
                    request_deserializer=grade__pb2.SubmitGradeRequest.FromString,
                    response_serializer=grade__pb2.SubmitGradeResponse.SerializeToString,
            ),
            'ListGrades': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGrades,
                    request_deserializer=grade__pb2.ListGradesRequest.FromString,
                    response_serializer=grade__pb2.ListGradesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grade.GradeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grade.GradeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GradeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitGrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grade.GradeService/SubmitGrade',
            grade__pb2.SubmitGradeRequest.SerializeToString,
            grade__pb2.SubmitGradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grade.GradeService/ListGrades',
            grade__pb2.ListGradesRequest.SerializeToString,
            grade__pb2.ListGradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
